name: UpdateZIP
'on':
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3.10'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install PyEnvironment
        uses: actions/setup-python@v4
        with:
          python-version: '${{ matrix.python-version }}'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy
          pip install pandas
          pip install requests
      - name: run UpdateZIP
        run: |
          cd ./fetchData
          python ./fetchData/fetchData.py
      - name: move new file
        run: |
          ls -la .
          ls -la ./fetchData
          mv ./fetchData/zip.json ./swissZip/v4/data/zip.json
      - name: Add to Repo
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_author: GithubAction <actions@github.com>
          commit_message: '[Bot] Update ZIP data'
          add: swissZIP/v4/data/zip.js
          add_options: '-u'
