name: UpdateZIP
on: 
  push:
  workflow_dispatch:
  schedule:
  - cron: '42 10,14,18 * * 1-5'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3.10'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install PyEnvironment
        uses: actions/setup-python@v4
        with:
          python-version: '${{ matrix.python-version }}'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy
          pip install pandas
          pip install requests
      - name: run UpdateZIP
        run: |
          cd fetchData
          python fetchData.py  
      - name: Update Repo
        uses: devops-infra/action-commit-push@master
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          commit_prefix: "[Bot] "
          commit_message: "Update ZIP data"
          force: true
      - name: Packagist Update
        uses: mnavarrocarter/packagist-update@v1.0.0    
        with:
          username: "ganti"
          api_token: ${{ secrets.packagist_token }}
          package_name: ganti/swisszip 
