name: UpdateZIP
on: 
  workflow_dispatch:
  schedule:
  - cron: '*/5 * * * 1-5'

jobs:
  job1:
    name: Debug
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3.10'
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install PyEnvironment
      uses: actions/setup-python@v4
      with:
        python-version: '${{ matrix.python-version }}'
        cache: 'pip'
    - name: Install dependencies
      run: |
        date
        python -m pip install --upgrade pip
        pip install numpy
        pip install pandas
        pip install requests
    - name: run UpdateZIP
      run: |
        cd fetchData
        python fetchData.py      
    - name: Add to Repo
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_author: GithubAction <actions@github.com>
        commit_message: '[Bot] Update ZIP data'
        branch: main
        file_pattern: 'zip.json'
        add_options: '-u'
    # Commit and push all changed files.
    - name: Update Repo
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git add ./swissZIP/v4/data/zip.json
        git commit -a -m "$(date +'%Y-%m-%d')"
        git push
